"""add temperature for users table

Revision ID: e3cbe1eba0a2
Revises: 7350cdff475e
Create Date: 2023-03-13 17:06:11.123997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cbe1eba0a2'
down_revision = '7350cdff475e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temperature')
    # ### end Alembic commands ###
